### ISSUE TITLE
Why your Application defined by class is right but in my project is wrong

### ISSUE THREAD

**Issue by zzguiji** [wsargent/play-slick-3.0#2]
In your project  controllers.Application is defined to a  class but a object.

in this case , the compiler will response message like follow :
"object Application is not a member of package controllers Note: class Application exists, but it has no companion object."

**Comment by wsargent** [comment]
You need to change your build.sbt to use DI:

https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection#Dependency-injecting-controllers
